apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: menu-service

  template:
    metadata:
      labels:
        app: menu-service

    spec:
      containers:
        - name: menu-service
          image: menu-service:1.0

          ports:
            - containerPort: 8082

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://menu-postgres:5432/menu_db

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILE