apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: saishtiwari
  POSTGRES_PASSWORD: pcps@123
  JWT_SECRET: my-super-secret-key-change-this-in-production

  