server:
  port: 8085

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # AUTH SERVICE
            - id: auth-service
              uri: http://auth-service:8081
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1

            # MENU SERVICE
            - id: menu-service
              uri: http://menu-service:8082
              predicates:
                - Path=/api/menu/**
              filters:
                - StripPrefix=1

            # ORDER SERVICE
            - id: order-service
              uri: http://order-service:8083
              predicates:
                - Path=/api/orders/**
              filters:
                - StripPrefix=1


  jwt:
    secret: ${JWT_SECRET}