server:
  port: 8085

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: menu-service
              uri: http://localhost:8082
              predicates:
                - Path=/menu/**
              filters:
                - StripPrefix=1

            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1