apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  AUTH_DB_HOST: "auth-postgres"
  MENU_DB_HOST: "menu-postgres"
  ORDER_DB_HOST: "order-postgres"

  DB_PORT: "5432"

  AUTH_SERVICE_PORT: "8081"
  MENU_SERVICE_PORT: "8082"
  ORDER_SERVICE_PORT: "8083"

  SPRING_PROFILE: "kubernetes"